namespace LightOps.NeuralLens.Data.Contract.Observability.Models;

/// <summary>
/// Represents the type of event in the observability system.
/// </summary>
public enum ObservabilityEventType
{
    /// <summary>
    /// Specific event type not specified.
    /// </summary>
    Unspecified = 0,

    /// <summary>
    /// Represents a system message in the context of Generative AI, which typically provides instructions or context for the AI model.
    /// </summary>
    GenAiSystemMessage = 1,

    /// <summary>
    /// Represents a user message in the context of Generative AI, which is typically the input provided by the user to the AI model.
    /// </summary>
    GenAiUserMessage = 2,

    /// <summary>
    /// Represents an assistant message in the context of Generative AI, which is typically the response generated by the AI model based on the user input.
    /// </summary>
    GenAiAssistantMessage = 3,

    /// <summary>
    /// Represents a tool message in the context of Generative AI, which is typically used to provide additional information or context for the AI model, or specific actions from external tools.
    /// </summary>
    GenAiToolMessage = 4,

    /// <summary>
    /// Represents a choice in the context of Generative AI, which typically refers to the response from the AI model.
    /// </summary>
    GenAiChoice = 5,
}