/* tslint:disable */
/* eslint-disable */
/**
 * Organization API
 * A Web API for organizations as part of the LightOps NeuralLens Platform.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationViewModel
 */
export interface OrganizationViewModel {
    /**
     * 
     * @type {string}
     * @memberof OrganizationViewModel
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationViewModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationViewModel
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof OrganizationViewModel
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof OrganizationViewModel
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the OrganizationViewModel interface.
 */
export function instanceOfOrganizationViewModel(value: object): value is OrganizationViewModel {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function OrganizationViewModelFromJSON(json: any): OrganizationViewModel {
    return OrganizationViewModelFromJSONTyped(json, false);
}

export function OrganizationViewModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationViewModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function OrganizationViewModelToJSON(json: any): OrganizationViewModel {
    return OrganizationViewModelToJSONTyped(json, false);
}

export function OrganizationViewModelToJSONTyped(value?: OrganizationViewModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'createdAt': ((value['createdAt']).toISOString()),
        'updatedAt': ((value['updatedAt']).toISOString()),
    };
}

