/* tslint:disable */
/* eslint-disable */
/**
 * Workspace API
 * A Web API for workspaces as part of the LightOps NeuralLens Platform.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateWorkspaceRequest
 */
export interface UpdateWorkspaceRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateWorkspaceRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateWorkspaceRequest
     */
    description: string | null;
}

/**
 * Check if a given object implements the UpdateWorkspaceRequest interface.
 */
export function instanceOfUpdateWorkspaceRequest(value: object): value is UpdateWorkspaceRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function UpdateWorkspaceRequestFromJSON(json: any): UpdateWorkspaceRequest {
    return UpdateWorkspaceRequestFromJSONTyped(json, false);
}

export function UpdateWorkspaceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateWorkspaceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
    };
}

export function UpdateWorkspaceRequestToJSON(json: any): UpdateWorkspaceRequest {
    return UpdateWorkspaceRequestToJSONTyped(json, false);
}

export function UpdateWorkspaceRequestToJSONTyped(value?: UpdateWorkspaceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

